import { Feature } from "../interfaces";
export let features: Feature[] = [
  {
    photo: 'feat1.png',
    type: 'Perimum',
    name: 'Renovated Apartment',
    loc: 'New Cairo, Egypt',
    beds: '4 Beds',
    baths: '2 Baths',
    sqft: '2500 Sqft',
    price: '$15,000',
    dis: '$20,000',
  },
  {
    photo: 'feat2.png',
    type: 'Perimum',
    name: 'Renovated Apartment',
    loc: 'New Cairo, Egypt',
    beds: '4 Beds',
    baths: '2 Baths',
    sqft: '2500 Sqft',
    price: '$10,000',
    dis: '$12,000',
  },
  {
    photo: 'feat3.png',
    type: 'Perimum',
    name: 'Renovated Apartment',
    loc: 'New Cairo, Egypt',
    beds: '4 Beds',
    baths: '2 Baths',
    sqft: '2500 Sqft',
    price: '$5,000',
    dis: '$8,000',
  },
  {
    photo: 'feat4.png',
    type: 'Perimum',
    name: 'Renovated Apartment',
    loc: 'New Cairo, Egypt',
    beds: '4 Beds',
    baths: '2 Baths',
    sqft: '2500 Sqft',
    price: '$20,000',
    dis: '$23,000',
  },
];
