import { Feature } from '../interfaces';
export let features: Feature[] = [
  {
    photo: 'feat1.png',
    type: 'home.featured-properties.feature.type',
    name: 'home.featured-properties.feature.name',
    loc: 'home.featured-properties.feature.loc',
    beds: 'home.featured-properties.feature.beds',
    baths: 'home.featured-properties.feature.baths',
    sqft: 'home.featured-properties.feature.sqft',
    price: '$15,000',
    dis: '$20,000',
  },
  {
    photo: 'feat2.png',
    type: 'home.featured-properties.feature.type',
    name: 'home.featured-properties.feature.name',
    loc: 'home.featured-properties.feature.loc',
    beds: 'home.featured-properties.feature.beds',
    baths: 'home.featured-properties.feature.baths',
    sqft: 'home.featured-properties.feature.sqft',
    price: '$10,000',
    dis: '$12,000',
  },
  {
    photo: 'feat3.png',
    type: 'home.featured-properties.feature.type',
    name: 'home.featured-properties.feature.name',
    loc: 'home.featured-properties.feature.loc',
    beds: 'home.featured-properties.feature.beds',
    baths: 'home.featured-properties.feature.baths',
    sqft: 'home.featured-properties.feature.sqft',
    price: '$5,000',
    dis: '$8,000',
  },
  {
    photo: 'feat4.png',
    type: 'home.featured-properties.feature.type',
    name: 'home.featured-properties.feature.name',
    loc: 'home.featured-properties.feature.loc',
    beds: 'home.featured-properties.feature.beds',
    baths: 'home.featured-properties.feature.baths',
    sqft: 'home.featured-properties.feature.sqft',
    price: '$20,000',
    dis: '$23,000',
  },
];
